name: apiKey

on:
  workflow_dispatch

env:
  OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
